const dataSeed = [
  {
    id: 1,
    nombre: "Monitor de Signos Vitales",
    marca: "Philips",
    modelo: "IntelliVue MX40",
    serie: "MX400123",
    ubicacion: "Sala de Urgencias",
    riesgo: "Alto",
    registro: "INVIMA2001-000123",
    activo_fijo: "EQ-0000001",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 2,
    nombre: "Ventilador Mecánico",
    marca: "Medtronic",
    modelo: "PB980",
    serie: "PB980456",
    ubicacion: "UCI",
    riesgo: "Crítico",
    registro: "INVIMA2002-000456",
    activo_fijo: "EQ-0000002",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 3,
    nombre: "Electrocardiógrafo",
    marca: "GE Healthcare",
    modelo: "MAC 5500 HD",
    serie: "MAC550789",
    ubicacion: "Cardiología",
    riesgo: "Medio",
    registro: "INVIMA2003-000789",
    activo_fijo: "EQ-0000003",
    estado: "EN REVISIÓN",
    observaciones: "",
  },
  {
    id: 4,
    nombre: "Desfibrilador",
    marca: "Zoll",
    modelo: "M Series",
    serie: "M123456",
    ubicacion: "Sala de Emergencias",
    riesgo: "Alto",
    registro: "INVIMA2004-000101",
    activo_fijo: "EQ-0000004",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 5,
    nombre: "Bomba de Infusión",
    marca: "Baxter",
    modelo: "Colleague 3",
    serie: "C312345",
    ubicacion: "UCI Neonatal",
    riesgo: "Medio",
    registro: "INVIMA2005-000202",
    activo_fijo: "EQ-0000005",
    estado: "FUERA DE SERVICIO",
    observaciones: "",
  },
  {
    id: 6,
    nombre: "Máquina de Anestesia",
    marca: "Drager",
    modelo: "Fabius Plus",
    serie: "FP789012",
    ubicacion: "Quirófano 1",
    riesgo: "Crítico",
    registro: "INVIMA2006-000303",
    activo_fijo: "EQ-0000006",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 7,
    nombre: "Ecodógrafo",
    marca: "Siemens",
    modelo: "Acuson X300",
    serie: "X300456",
    ubicacion: "Imágenes Diagnósticas",
    riesgo: "Medio",
    registro: "INVIMA2007-000404",
    activo_fijo: "EQ-0000007",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 8,
    nombre: "Analizador de Gases en Sangre",
    marca: "Radiometer",
    modelo: "ABL90 FLEX",
    serie: "ABL90123",
    ubicacion: "Laboratorio",
    riesgo: "Alto",
    registro: "INVIMA2008-000505",
    activo_fijo: "EQ-0000008",
    estado: "EN REVISIÓN",
    observaciones: "",
  },
  {
    id: 9,
    nombre: "Centrífuga",
    marca: "Eppendorf",
    modelo: "5804 R",
    serie: "5804R678",
    ubicacion: "Laboratorio",
    riesgo: "Bajo",
    registro: "INVIMA2009-000606",
    activo_fijo: "EQ-0000009",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 10,
    nombre: "Incubadora Neonatal",
    marca: "GE Healthcare",
    modelo: "Giraffe Omnibed",
    serie: "GO123456",
    ubicacion: "UCI Neonatal",
    riesgo: "Crítico",
    registro: "INVIMA2010-000707",
    activo_fijo: "EQ-0000010",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 11,
    nombre: "Monitor Fetal",
    marca: "Philips",
    modelo: "Avalon FM30",
    serie: "FM301234",
    ubicacion: "Maternidad",
    riesgo: "Medio",
    registro: "INVIMA2011-000808",
    activo_fijo: "EQ-0000011",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 12,
    nombre: "Lámpara de Fototerapia",
    marca: "Natus",
    modelo: "BiliSoft",
    serie: "BS123456",
    ubicacion: "UCI Neonatal",
    riesgo: "Bajo",
    registro: "INVIMA2012-000909",
    activo_fijo: "EQ-0000012",
    estado: "FUERA DE SERVICIO",
    observaciones: "",
  },
  {
    id: 13,
    nombre: "Cámara Hiperbárica",
    marca: "Sechrist",
    modelo: "3200H",
    serie: "3200H123",
    ubicacion: "Terapia Hiperbárica",
    riesgo: "Alto",
    registro: "INVIMA2013-000101",
    activo_fijo: "EQ-0000013",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 14,
    nombre: "Máquina de Diálisis",
    marca: "Fresenius",
    modelo: "4008S",
    serie: "4008S456",
    ubicacion: "Nefrología",
    riesgo: "Crítico",
    registro: "INVIMA2014-000202",
    activo_fijo: "EQ-0000014",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 15,
    nombre: "Equipo de Rayos X",
    marca: "Siemens",
    modelo: "Multix Fusion",
    serie: "MF123456",
    ubicacion: "Radiología",
    riesgo: "Alto",
    registro: "INVIMA2015-000303",
    activo_fijo: "EQ-0000015",
    estado: "EN REVISIÓN",
    observaciones: "",
  },
  {
    id: 16,
    nombre: "Resonador Magnético",
    marca: "Philips",
    modelo: "Ingenia 1.5T",
    serie: "I1.5T789",
    ubicacion: "Imágenes Diagnósticas",
    riesgo: "Crítico",
    registro: "INVIMA2016-000404",
    activo_fijo: "EQ-0000016",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 17,
    nombre: "Tomógrafo",
    marca: "GE Healthcare",
    modelo: "Revolution EVO",
    serie: "RE123456",
    ubicacion: "Radiología",
    riesgo: "Crítico",
    registro: "INVIMA2017-000505",
    activo_fijo: "EQ-0000017",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 18,
    nombre: "Equipo de Ultrasonido",
    marca: "Samsung",
    modelo: "HS50",
    serie: "HS501234",
    ubicacion: "Imágenes Diagnósticas",
    riesgo: "Medio",
    registro: "INVIMA2018-000606",
    activo_fijo: "EQ-0000018",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 19,
    nombre: "Máquina de Hemodiálisis",
    marca: "Baxter",
    modelo: "Artis Physio",
    serie: "AP123456",
    ubicacion: "Nefrología",
    riesgo: "Crítico",
    registro: "INVIMA2019-000707",
    activo_fijo: "EQ-0000019",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 20,
    nombre: "Equipo de Endoscopia",
    marca: "Olympus",
    modelo: "EVIS EXERA III",
    serie: "EE312345",
    ubicacion: "Gastroenterología",
    riesgo: "Alto",
    registro: "INVIMA2020-000808",
    activo_fijo: "EQ-0000020",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 21,
    nombre: "Monitor de Presión Intracraneal",
    marca: "Integra",
    modelo: "Camino 110-4B",
    serie: "C1104B123",
    ubicacion: "Neurocirugía",
    riesgo: "Crítico",
    registro: "INVIMA2021-000909",
    activo_fijo: "EQ-0000021",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 22,
    nombre: "Equipo de Cirugía Laparoscópica",
    marca: "Stryker",
    modelo: "1588 HD",
    serie: "1588HD456",
    ubicacion: "Quirófano 2",
    riesgo: "Alto",
    registro: "INVIMA2022-000101",
    activo_fijo: "EQ-0000022",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 23,
    nombre: "Equipo de Hemodinámica",
    marca: "Philips",
    modelo: "Allura Xper FD20",
    serie: "AXFD20123",
    ubicacion: "Hemodinámica",
    riesgo: "Crítico",
    registro: "INVIMA2023-000202",
    activo_fijo: "EQ-0000023",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 24,
    nombre: "Equipo de Radioterapia",
    marca: "Varian",
    modelo: "TrueBeam",
    serie: "TB123456",
    ubicacion: "Oncología",
    riesgo: "Crítico",
    registro: "INVIMA2024-000303",
    activo_fijo: "EQ-0000024",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 25,
    nombre: "Equipo de Mamografía",
    marca: "Hologic",
    modelo: "Selenia Dimensions",
    serie: "SD123456",
    ubicacion: "Mastología",
    riesgo: "Alto",
    registro: "INVIMA2025-000404",
    activo_fijo: "EQ-0000025",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 26,
    nombre: "Equipo de Densitometría Ósea",
    marca: "GE Healthcare",
    modelo: "Lunar iDXA",
    serie: "LIDXA123",
    ubicacion: "Reumatología",
    riesgo: "Medio",
    registro: "INVIMA2026-000505",
    activo_fijo: "EQ-0000026",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 27,
    nombre: "Equipo de Terapia Respiratoria",
    marca: "ResMed",
    modelo: "Stellar 150",
    serie: "ST150123",
    ubicacion: "Neumología",
    riesgo: "Medio",
    registro: "INVIMA2027-000606",
    activo_fijo: "EQ-0000027",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 28,
    nombre: "Equipo de Electroencefalografía",
    marca: "Natus",
    modelo: "EEG Ultra",
    serie: "EEGU123",
    ubicacion: "Neurología",
    riesgo: "Medio",
    registro: "INVIMA2028-000707",
    activo_fijo: "EQ-0000028",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 29,
    nombre: "Equipo de Polisomnografía",
    marca: "Philips",
    modelo: "Alice 6",
    serie: "A6123456",
    ubicacion: "Medicina del Sueño",
    riesgo: "Medio",
    registro: "INVIMA2029-000808",
    activo_fijo: "EQ-0000029",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 30,
    nombre: "Equipo de Hemofiltración",
    marca: "Fresenius",
    modelo: "multiFiltrate",
    serie: "MF123456",
    ubicacion: "UCI",
    riesgo: "Crítico",
    registro: "INVIMA2030-000909",
    activo_fijo: "EQ-0000030",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 31,
    nombre: "Equipo de Cirugía Robótica",
    marca: "Intuitive Surgical",
    modelo: "da Vinci Xi",
    serie: "DVXi123",
    ubicacion: "Quirófano 3",
    riesgo: "Crítico",
    registro: "INVIMA2031-000101",
    activo_fijo: "EQ-0000031",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 32,
    nombre: "Equipo de Oftalmología",
    marca: "Zeiss",
    modelo: "Cirrus 5000",
    serie: "C5000123",
    ubicacion: "Oftalmología",
    riesgo: "Medio",
    registro: "INVIMA2032-000202",
    activo_fijo: "EQ-0000032",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 33,
    nombre: "Equipo de Audiometría",
    marca: "Interacoustics",
    modelo: "Affinity 2.0",
    serie: "A2.0123",
    ubicacion: "Audiología",
    riesgo: "Bajo",
    registro: "INVIMA2033-000303",
    activo_fijo: "EQ-0000033",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 34,
    nombre: "Equipo de Espirometría",
    marca: "CareFusion",
    modelo: "MasterScreen",
    serie: "MS123456",
    ubicacion: "Neumología",
    riesgo: "Bajo",
    registro: "INVIMA2034-000404",
    activo_fijo: "EQ-0000034",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 35,
    nombre: "Equipo de Diatermia",
    marca: "Chattanooga",
    modelo: "Intelect Mobile",
    serie: "IM123456",
    ubicacion: "Fisioterapia",
    riesgo: "Medio",
    registro: "INVIMA2035-000505",
    activo_fijo: "EQ-0000035",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 36,
    nombre: "Equipo de Laserterapia",
    marca: "BTL",
    modelo: "BTL-6000",
    serie: "BTL6000123",
    ubicacion: "Fisioterapia",
    riesgo: "Medio",
    registro: "INVIMA2036-000606",
    activo_fijo: "EQ-0000036",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 37,
    nombre: "Equipo de Magnetoterapia",
    marca: "ASA",
    modelo: "Magnum XL",
    serie: "MXL123456",
    ubicacion: "Fisioterapia",
    riesgo: "Bajo",
    registro: "INVIMA2037-000707",
    activo_fijo: "EQ-0000037",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 38,
    nombre: "Equipo de Ultrasonido Terapéutico",
    marca: "Enraf-Nonius",
    modelo: "Sonopuls 490",
    serie: "SP490123",
    ubicacion: "Fisioterapia",
    riesgo: "Bajo",
    registro: "INVIMA2038-000808",
    activo_fijo: "EQ-0000038",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 39,
    nombre: "Equipo de Electroterapia",
    marca: "Zimmer",
    modelo: "Soleo Galva",
    serie: "SG123456",
    ubicacion: "Fisioterapia",
    riesgo: "Medio",
    registro: "INVIMA2039-000909",
    activo_fijo: "EQ-0000039",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 40,
    nombre: "Equipo de Crioterapia",
    marca: "CryoScience",
    modelo: "Cryo Arctic",
    serie: "CA123456",
    ubicacion: "Fisioterapia",
    riesgo: "Medio",
    registro: "INVIMA2040-000101",
    activo_fijo: "EQ-0000040",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 41,
    nombre: "Equipo de Hidroterapia",
    marca: "HydroWorx",
    modelo: "2000 Series",
    serie: "HW2000123",
    ubicacion: "Fisioterapia",
    riesgo: "Medio",
    registro: "INVIMA2041-000202",
    activo_fijo: "EQ-0000041",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 42,
    nombre: "Equipo de Terapia de Onda de Choque",
    marca: "Storz Medical",
    modelo: "Duolith SD1",
    serie: "DSD1123456",
    ubicacion: "Fisioterapia",
    riesgo: "Medio",
    registro: "INVIMA2042-000303",
    activo_fijo: "EQ-0000042",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 43,
    nombre: "Equipo de Terapia de Luz",
    marca: "Lumenis",
    modelo: "M22",
    serie: "M22123456",
    ubicacion: "Dermatología",
    riesgo: "Medio",
    registro: "INVIMA2043-000404",
    activo_fijo: "EQ-0000043",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 44,
    nombre: "Equipo de Terapia de Radiofrecuencia",
    marca: "BTL",
    modelo: "BTL-6000 TR",
    serie: "BTL6000TR123",
    ubicacion: "Dermatología",
    riesgo: "Medio",
    registro: "INVIMA2044-000505",
    activo_fijo: "EQ-0000044",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 45,
    nombre: "Equipo de Terapia de Ultrasonido Estético",
    marca: "Ulthera",
    modelo: "Ultherapy",
    serie: "UT123456",
    ubicacion: "Dermatología",
    riesgo: "Medio",
    registro: "INVIMA2045-000606",
    activo_fijo: "EQ-0000045",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 46,
    nombre: "Equipo de Terapia de Luz Pulsada",
    marca: "Lumenis",
    modelo: "M22 IPL",
    serie: "M22IPL123",
    ubicacion: "Dermatología",
    riesgo: "Medio",
    registro: "INVIMA2046-000707",
    activo_fijo: "EQ-0000046",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 47,
    nombre: "Equipo de Terapia de Microdermoabrasión",
    marca: "Silhouet-Tone",
    modelo: "Derma Pod",
    serie: "DP123456",
    ubicacion: "Dermatología",
    riesgo: "Bajo",
    registro: "INVIMA2047-000808",
    activo_fijo: "EQ-0000047",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 48,
    nombre: "Equipo de Terapia de Oxigenoterapia",
    marca: "OxyHealth",
    modelo: "Vitaeris 320",
    serie: "V320123456",
    ubicacion: "Dermatología",
    riesgo: "Bajo",
    registro: "INVIMA2048-000909",
    activo_fijo: "EQ-0000048",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 49,
    nombre: "Equipo de Terapia de Presoterapia",
    marca: "Lympha Press",
    modelo: "Optimal Plus",
    serie: "OP123456",
    ubicacion: "Fisioterapia",
    riesgo: "Bajo",
    registro: "INVIMA2049-000101",
    activo_fijo: "EQ-0000049",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 50,
    nombre: "Equipo de Terapia de Vacuoterapia",
    marca: "Starvac",
    modelo: "DXtwin",
    serie: "DX123456",
    ubicacion: "Fisioterapia",
    riesgo: "Bajo",
    registro: "INVIMA2050-000202",
    activo_fijo: "EQ-0000050",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 51,
    nombre: "Equipo de Terapia de Fototerapia",
    marca: "Waldmann",
    modelo: "UV 100L",
    serie: "UV100L123",
    ubicacion: "Dermatología",
    riesgo: "Bajo",
    registro: "INVIMA2051-000303",
    activo_fijo: "EQ-0000051",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 52,
    nombre: "Equipo de Terapia de Carboxiterapia",
    marca: "Carbossi",
    modelo: "Carbossi 2000",
    serie: "C2000123",
    ubicacion: "Dermatología",
    riesgo: "Bajo",
    registro: "INVIMA2052-000404",
    activo_fijo: "EQ-0000052",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 53,
    nombre: "Equipo de Terapia de Criolipólisis",
    marca: "CoolSculpting",
    modelo: "CS123456",
    serie: "CS123456",
    ubicacion: "Dermatología",
    riesgo: "Medio",
    registro: "INVIMA2053-000505",
    activo_fijo: "EQ-0000053",
    estado: "OPERATIVO",
    observaciones: "",
  },
  {
    id: 54,
    nombre: "Equipo de Terapia de HIFU",
    marca: "Ulthera",
    modelo: "Ultherapy",
    serie: "UT654321",
    ubicacion: "Dermatología",
    riesgo: "Medio",
    registro: "INVIMA2054-000606",
    activo_fijo: "EQ-0000054",
    estado: "OPERATIVO",
    observaciones: "",
  },
];

export default dataSeed;
